"""PLANLOOP_HOME resolution and initialization helpers."""
from __future__ import annotations

import os
from importlib import resources
from pathlib import Path

PLANLOOP_HOME_ENV = "PLANLOOP_HOME"
DEFAULT_HOME_NAME = ".planloop"

CONFIG_FILE_NAME = "config.yml"
CURRENT_SESSION_POINTER = "current_session"
PROMPTS_DIR = "prompts"
DEFAULT_PROMPT_SET = "core-v1"
MESSAGES_DIR = "messages"
SESSIONS_DIR = "sessions"

_TEMPLATES_PACKAGE = "planloop.templates"
_PROMPTS_TEMPLATE_SUBDIR = "prompts"
_MESSAGES_TEMPLATE_SUBDIR = "messages"

DEFAULT_CONFIG_YAML = """\n# Autogenerated by planloop initialize_home\nversion: 1\nprompt_set: core-v1\nhistory:\n  enabled: false\nlogging:\n  level: INFO\nsafe_modes:\n  update:\n    dry_run: false\n    no_plan_edit: false\n    strict: false\n"""


def _expand_path(raw_path: str) -> Path:
    """Expand user/relative components for PLANLOOP_HOME overrides."""
    return Path(raw_path).expanduser().resolve()


def get_home() -> Path:
    """Return the PLANLOOP_HOME directory, creating it when missing."""
    env_override = os.environ.get(PLANLOOP_HOME_ENV)
    if env_override:
        home_path = _expand_path(env_override)
    else:
        home_path = (Path.home() / DEFAULT_HOME_NAME).resolve()
    home_path.mkdir(parents=True, exist_ok=True)
    return home_path


def _write_file_once(path: Path, contents: str) -> None:
    """Write `contents` to `path` if it does not exist yet."""
    if not path.exists():
        path.write_text(contents, encoding="utf-8")


def _seed_from_templates(template_subdir: str, destination: Path) -> None:
    """Copy prompt/message templates into PLANLOOP_HOME if missing."""
    traversable = resources.files(_TEMPLATES_PACKAGE) / template_subdir
    for entry in traversable.iterdir():
        target = destination / entry.name
        if entry.is_dir():
            target.mkdir(parents=True, exist_ok=True)
            _seed_from_templates(f"{template_subdir}/{entry.name}", target)
        else:
            if not target.exists():
                target.write_text(entry.read_text(encoding="utf-8"), encoding="utf-8")


def initialize_home() -> Path:
    """Create PLANLOOP_HOME directories + config/templates if missing."""
    home_dir = get_home()

    dirs = [
        home_dir / SESSIONS_DIR,
        home_dir / PROMPTS_DIR,
        home_dir / PROMPTS_DIR / DEFAULT_PROMPT_SET,
        home_dir / MESSAGES_DIR,
    ]
    for path in dirs:
        path.mkdir(parents=True, exist_ok=True)

    _seed_from_templates(_PROMPTS_TEMPLATE_SUBDIR, home_dir / PROMPTS_DIR)
    _seed_from_templates(_MESSAGES_TEMPLATE_SUBDIR, home_dir / MESSAGES_DIR)

    _write_file_once(home_dir / CONFIG_FILE_NAME, DEFAULT_CONFIG_YAML)
    _write_file_once(home_dir / CURRENT_SESSION_POINTER, "")
    return home_dir


__all__ = [
    "get_home",
    "initialize_home",
    "PLANLOOP_HOME_ENV",
    "DEFAULT_HOME_NAME",
    "CONFIG_FILE_NAME",
    "CURRENT_SESSION_POINTER",
    "PROMPTS_DIR",
    "DEFAULT_PROMPT_SET",
    "MESSAGES_DIR",
    "SESSIONS_DIR",
]
